This version (4.2.2) was changed to fix a bug in casapy-42.2.30986-pipe-1-64b/lib64/python2.7/get_user.py
